version: '3'

services:
    mariadb:
        container_name: mariadb
        image: mariadb
        expose:
            - 3306
        restart: unless-stopped
        networks:
            - inception
        env_file: .env
        build: requirements/mariadb
        volumes:
            - mariadb:/var/lib/mysql

    wordpress:
        container_name: wordpress
        image: wordpress
        expose:
            - 9000
        restart: unless-stopped
        networks:
            - inception
        env_file: .env
        build: requirements/wordpress
        depends_on:
            - mariadb
        volumes:
            - wordpress:/var/www/html/wordpress

    nginx:
        container_name: nginx
        image: nginx
        build: requirements/nginx
        ports:
            - 443:443
        restart: always
        networks:
            - inception
        volumes:
            - wordpress:/var/www/html/wordpress
        depends_on:
            - wordpress

networks:
    inception:
        driver: bridge

volumes:
    mariadb:
        driver_opts:
            type: none
            device: /home/recarlie/data/mysql
            o: bind
    wordpress:
        driver_opts:
            type: none
            device: /home/recarlie/data/wordpress
            o: bind
